services:
  - type: web
    name: calendarios-map
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SUPABASE_URL
        value: https://lqdpirsfzodmbeyoivww.supabase.co
      - key: PYTHON_VERSION
        value: 3.11.0